base_shop/base_shop/urls.py
from django.contrib import admin
from django.urls import path,include
from django.shortcuts import redirect
from django.conf.urls.static import static # 画像用
from django.conf import settings # 画像用

urlpatterns = [
    path('admin/logout/', lambda request: redirect('/products/home/')),
    path('admin/', admin.site.urls),
    path('users/', include('users.urls')),
    path('products/', include('products.urls')),
    path('orders/', include('orders.urls')),
    path('', include('home.urls')),
]
urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT) # 画像用

base_shop/home/urls.py
from django.urls import path
from .views import HomeView
from . import views

urlpatterns = [
    path('', HomeView.as_view(), name='home'),  
    path('error-test/', views.trigger_error, name='error_test'),
]

base_shop/orders/urls.py
from django.urls import path
from . import views

app_name = 'orders'

urlpatterns = [
  path('cart/', views.view_cart, name='view_cart'),
  path('add/<product_id>/', views.add_to_cart, name='add_to_cart'),
  path('remove/<item_id>/', views.remove_from_cart, name='remove_from_cart'),
  path('confirm/', views.order_confirm_view, name='confirm'),
  path('complete/', views.order_complete_view, name='order_complete'),
  path('address', views.change_address_view, name='address'),
  path('buy-now/<product_id>/', views.buy_now, name='buy_now')
]

base_shop/products/urls.py
from django.urls import path
from . import views
from .views import ProductListView, ProductDetailView

app_name = 'products'

urlpatterns = [
  path('home/', views.HomeView.as_view(), name='home'),
  path('admin_login/', views.AdminLoginView.as_view(), name='admin_login'),
  path('list/', ProductListView.as_view(), name='product_list'),
  path('detail/<slug>', ProductDetailView.as_view(), name='product_detail')
]

base_shop/home/models.py
from django.db import models

# Create your models here.

base_shop/products/models.py
from django.db import models
from django.utils.text import slugify

# Create your models here.
class Product(models.Model):
  name = models.CharField("商品名", max_length=100)
  category = models.CharField("カテゴリ", max_length=50)
  manufacturer = models.CharField("メーカー" ,max_length=50)
  color = models.CharField("色(カラー)" ,max_length=30)
  position = models.CharField("ポジション(グローブのみ)" ,max_length=30)
  description = models.TextField("説明")
  image = models.ImageField("画像" ,upload_to='product_images')
  price = models.PositiveBigIntegerField("金額")
  slug = models.SlugField("スラッグ" ,unique=True, blank=True)

  def __str__(self):
    return self.name  # 商品名を表示

  class Meta:
    verbose_name = '商品'
    verbose_name_plural = '商品一覧'

def save(self, *args, **kwargs):
  if not self.slug:
    self.slug = slugify(self.name) 
  super().save()

  def __str__(self):
    return self.name
  

base_shop/users/forms.py
from django import forms
from .models import User
from django.contrib.auth.password_validation import validate_password

class RegistForm(forms.ModelForm):

  class Meta:
    model = User
    fields = ['username', 'email', 'password']
    widgets = {
    'password': forms.PasswordInput(),
    }
    labels = {
    'username': 'お名前(フルーネーム)',
    'email': 'メールアドレス',
    'password': 'パスワード',
    }

  def save(self, commit=False):
    user = super().save(commit=False)
    validate_password(self.cleaned_data['password'], user)
    user.set_password(self.cleaned_data['password'])
    user.save()
    return user
  
  def __init__(self, *args, **kwargs):
    super().__init__(*args, **kwargs)
    self.label_suffix = ''

class UserLoginForm(forms.Form):
  email = forms.EmailField(label='メールアドレス', label_suffix='')
  password = forms.CharField(label='パスワード', widget=forms.PasswordInput(), label_suffix='')

base_shop/home/views.py
from django.views.generic import TemplateView

class HomeView(TemplateView):
  template_name = 'home/home.html'
  
def trigger_error(request):
    raise Exception("これはテスト用のサーバーエラーです")

base_shop/products/views.py
from django.shortcuts import render, redirect
from django.contrib.auth import authenticate, login
from django.views import View
from django.views.generic import TemplateView, ListView, DetailView
from .models import Product


class HomeView(TemplateView):
  template_name = 'products/home.html'
  

class AdminLoginView(View):
  def post(self, request):
    email = request.POST['email']
    password = request.POST['password']
    user = authenticate(request, email=email, password=password)

    if user is not None and user.is_staff:
      login(request, user)
      return redirect('/admin/')
    else:
      return render(request, 'products/home.html', {
        'error':"メールアドレスまたはパスワードが間違っています"
      })
  def get(self, request):
    return redirect('products:home')

class ProductListView(ListView):
  model = Product
  template_name = 'products/product_list.html'
  context_object_name = 'products'

class ProductDetailView(DetailView):
  model = Product
  template_name = 'products/product_detail.html'
  context_object_name = 'product'

base_shop/templates/products/home.html
{% extends 'base.html' %}
<h2>管理者ログイン</h2>
<form method="post" action="{% url 'products:admin_login' %}">
  {% csrf_token %}


  <button type="submit">ログイン</button>
</form>

{% if error %}
  <p style="color: red;">{{ error }}</p>
{% endif %}


{% load static %}
{% block title %}ログイン{% endblock %}

{% block content %}
<div class="container my-5 w-50 mx-auto text-center">
  <form method="POST" action="{% url 'products:admin_login' %}">
    <h2 class="h3 mb-3 fw-normal">管理者ログイン</h2>
    {% csrf_token %}
    <div class="form-group w-50 mx-auto mt-5 text-start">
      <label for="id_email" class="form-label">メールアドレス</label>
      <input type="email" name="email" class="form-control" id="id_email" placeholder="name@example.com">
    </div>
    <div class="form-group w-50 mx-auto mt-5 text-start">
      <label for="id_password" class="form-label">パスワード</label>
      <input type="password" name="password" class="form-control" id="id_password" placeholder="password">
    </div>
    <div class="mt-5 w-50 mx-auto d-flex justify-content-between">
      <a href="{% url 'home' %}" class="btn btn-secondary ms-5 mt-3">キャンセル</a>
      <button class="button me-5 mt-3" type="submit">ログイン</button>
    </div>
  </form>
</div>
{% endblock %}

base_shop/templates/products/product_detail.html
{% extends 'base.html' %}
{% block title %}{{product.name}}詳細{% endblock %}

{% block content %}
<div class="container mt-5">
  <h2 class="text-center mb-4">{{ product.name }}の詳細</h2>

  <!-- 商品画像 -->
  <div class="text-center mb-4">
    <img src="{{ product.image.url }}" alt="{{ product.name }}" class="img-fluid product_detail_img">
  </div>

  <!-- 商品詳細テーブル -->
  <div class="mb-4">
    <table class="w-50 mx-auto product_detail_table">
      <tbody>
        <tr>
          <th scope="row">商品名</th>
          <td>{{ product.name }}</td>
        </tr>
        <tr>
        <tr>
          <th>メーカー</th>
          <td>{{ product.manufacturer}}</td>
        </tr>
        <tr>
          <th>種別</th>
          <td>{{ product.category}}</td>
        </tr>
        <tr>
          <th>カラー</th>
          <td>{{ product.color}}</td>
        </tr>
        <tr>
          <th>ポジション</th>
          <td>{{ product.position}}</td>
        </tr>
        <th scope="row">価格</th>
        <td>￥{{ product.price }}</td>
        </tr>
        <tr>
          <th scope="row">説明</th>
          <td>{{ product.description }}</td>
        </tr>
      </tbody>
    </table>
  </div>

  <!-- カート追加ボタン -->
  <div class="text-center w-50 d-flex justify-content-around mx-auto mb-5 detail-btn-wrapper">
    <a href="{% url 'products:product_list' %}" class="button btn_back">商品一覧に戻る</a>
    <input type="hidden" id="csrf-token" value="{{ csrf_token }}">
    <div id="alert-box" class="alert alert-info alert-dismissible fade show mt-4 w-25 detail-fade-in d-none" role="alert">
      <span id="alert-message">商品を追加しました</span>
      <button type="button" class="btn-close" data-bs-dismiss="alert" aria-label="Close"></button>
    </div>
    <button id="add-to-cart-btn" class="button" data-product-id="{{product.id}}" data-url="{% url 'orders:add_to_cart' product.id %}">カートに追加</button>
    <form method="POST" action="{% url 'orders:buy_now' product.id %}">
      {% csrf_token %}
      <button type="submit" class="button">この商品を購入する</button>
    </form>
  </div>
</div>

{% endblock %}

base_shop/templates/products/product_list.html
{% extends 'base.html' %}
{% block title %}商品一覧{% endblock %}

{% block content %}
<h2 class="text-center mt-5">商品一覧</h2>
{% if products %}
<div class="container mt-5">
  <div class="row">
    {% for product in products %}
    <div class="col-md-4 mb-4">
      <div class="card h-100">
        <img src="{{ product.image.url }}" class="card-img-top" alt="{{ product.name }}" height="420">
        <div class="card-body">
          <h5 class="card-title">{{ product.name }}</h5>
          <p class="card-text">{{ product.description|truncatechars:50 }}</p>
          <p class="card-text text-muted">￥{{ product.price }}</p>
          <a href="{% url 'products:product_detail' product.slug %}" class="button">詳細を見る</a>
        </div>
      </div>
    </div>
    {% endfor %}
  </div>
</div>
{% else %}
<p>商品はありません</p>
{% endif %}
{% endblock %}