base_shop/base_shop/urls.py
from django.contrib import admin
from django.urls import path,include
from django.shortcuts import redirect
from django.conf.urls.static import static # 画像用
from django.conf import settings # 画像用

urlpatterns = [
    path('admin/logout/', lambda request: redirect('/products/home/')),
    path('admin/', admin.site.urls),
    path('users/', include('users.urls')),
    path('products/', include('products.urls')),
    path('orders/', include('orders.urls')),
    path('', include('home.urls')),
]
urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT) # 画像用

base_shop/home/urls.py
from django.urls import path
from .views import HomeView
from . import views

urlpatterns = [
    path('', HomeView.as_view(), name='home'),  
    path('error-test/', views.trigger_error, name='error_test'),
]

base_shop/products/urls.py
from django.urls import path
from . import views
from .views import ProductListView, ProductDetailView

app_name = 'products'

urlpatterns = [
  path('home/', views.HomeView.as_view(), name='home'),
  path('admin_login/', views.AdminLoginView.as_view(), name='admin_login'),
  path('list/', ProductListView.as_view(), name='product_list'),
  path('detail/<slug>', ProductDetailView.as_view(), name='product_detail')
]

base_shop/users/urls.py
from django.urls import path
from .views import (
RegistUserView, UserLoginView,
UserLogoutView,UserView,EditUserAndAddressView
)
from . import views

app_name = 'users'
urlpatterns = [
path('regist/', RegistUserView.as_view(), name='regist'),
path('login/', UserLoginView.as_view(), name='user_login'),
path('logout/', UserLogoutView.as_view(), name='user_logout'),
path('user/', UserView.as_view(), name='user'),
path('edit/', views.EditUserAndAddressView.as_view(), name='edit')
]

base_shop/users/models.py
from django.db import models
from django.contrib.auth.models import(
BaseUserManager, AbstractBaseUser, PermissionsMixin
)
from django.urls import reverse_lazy

class UserManager(BaseUserManager):
  def create_user(self, username, email, password):
    if not email:
      raise ValueError('Emailを入力してください')
    if not password:
      raise ValueError('Passwordを入力してください')
    user = self.model(
    username=username,
    email=self.normalize_email(email)
    )
    user.set_password(password)
    user.save()
    return user
  
  def create_superuser(self, username, email, password=None):
    user = self.create_user(
      username=username,
      email=email,
      password=password,
    )
    user.is_staff = True
    user.is_superuser = True
    user.save(using=self._db)
    return user

class User(AbstractBaseUser, PermissionsMixin):
  username = models.CharField('名前' ,max_length=150)
  email = models.EmailField('メールアドレス' ,max_length=255, unique=True)
  is_active = models.BooleanField(default=True)
  is_staff = models.BooleanField(default=False)
  is_superuser = models.BooleanField(default=False)

  USERNAME_FIELD = 'email'
  REQUIRED_FIELDS = ['username']
  
  objects = UserManager()
  
  def get_absolute_url(self):
    return reverse_lazy('users:home')

class Address(models.Model):
  user = models.OneToOneField(User, on_delete=models.CASCADE, related_name='address')
  postal_code = models.CharField('郵便番号' , max_length=10, blank=True, null=True)
  country = models.CharField('国名' , max_length=50, blank=True, null=True)
  prefecture = models.CharField('都道府県' , max_length=50, blank=True, null=True)
  city = models.CharField('市区町村' , max_length=100, blank=True, null=True)
  street = models.CharField('番地以下' , max_length=255, blank=True, null=True)

  def __str__(self):
    parts = [self.postal_code,self.country, self.prefecture, self.city, self.street]
    return " ".join(filter(None, parts)) or "住所未設定"

base_shop/users/forms.py
from django import forms
from .models import User
from django.contrib.auth.password_validation import validate_password

class RegistForm(forms.ModelForm):

  class Meta:
    model = User
    fields = ['username', 'email', 'password']
    widgets = {
    'password': forms.PasswordInput(),
    }
    labels = {
    'username': 'お名前(フルーネーム)',
    'email': 'メールアドレス',
    'password': 'パスワード',
    }

  def save(self, commit=False):
    user = super().save(commit=False)
    validate_password(self.cleaned_data['password'], user)
    user.set_password(self.cleaned_data['password'])
    user.save()
    return user
  
  def __init__(self, *args, **kwargs):
    super().__init__(*args, **kwargs)
    self.label_suffix = ''

class UserLoginForm(forms.Form):
  email = forms.EmailField(label='メールアドレス', label_suffix='')
  password = forms.CharField(label='パスワード', widget=forms.PasswordInput(), label_suffix='')

base_shop/users/views.py
from django.shortcuts import render, redirect
from django.views.generic import(
TemplateView, CreateView, FormView, View,UpdateView
)
from django.contrib.auth import authenticate, login, logout, get_user_model
from django.contrib.auth.mixins import LoginRequiredMixin
from django.urls import reverse_lazy
from django.contrib import messages
from django.views import View
from django import forms
from orders.models import Order
from .models import Address
from .forms import UserLoginForm
import pycountry

User = get_user_model()

PREFECTURES = ["北海道", "青森県", "岩手県", "宮城県", "秋田県", "山形県", "福島県", "茨城県", "栃木県", "群馬県", "埼玉県", "千葉県", "東京都", "神奈川県", "新潟県", "富山県", "石川県", "福井県", "山梨県", "岐阜県", "静岡県", "愛知県", "滋賀県", "京都府", "大阪府", "兵庫県", "奈良県", "和歌山県", "鳥取県", "島根県", "岡山県", "秋田県", "広島県", "山口県", "徳島県", "香川県", "愛媛県", "高知県", "福岡県", "佐賀県", "長崎県", "熊本県", "大分県", "宮崎県", "鹿児島県", "沖縄県"]

def get_country_list():
  return [country.name for country in pycountry.countries]

class RegistUserView(View):
  def get(self, request, *args, **kwargs):
    countries = get_country_list()
    return render(request, 'users/regist.html', {
      "countries": countries,
      "prefectures": PREFECTURES
    })
  
  def post(self, request, *args, **kwargs):
    # ユーザー情報の取得
    username = request.POST.get('username')
    email = request.POST.get('email')
    password = request.POST.get('password')

    # 住所情報の取得
    postal_code = request.POST.get('postal_code') or ""
    country = request.POST.get('country') or ""
    prefecture = request.POST.get('prefecture') or ""
    city = request.POST.get('city') or ""
    street = request.POST.get('street') or ""

    # 名前・メールアドレス・パスワードどれかがなかった場合の処理
    if not username or not email or not password:
      messages.error(request, "名前・メールアドレス・パスワード全て必須です")
      return render(request, 'users/regist.html')
    
    # メールアドレスが重複したいた場合の処理
    if User.objects.filter(email=email).exists():
      messages.error(request, "このメールアドレスは既に登録されています")
      return render(request, 'users/regist.html')
    
    #ユーザー情報の登録処理
    user = User.objects.create(
      username=username,
      email=email
    )
    user.set_password(password)
    user.save()

    #住所情報の登録処理
    Address.objects.create(
      user=user,
      postal_code=postal_code,
      country=country,
      prefecture=prefecture,
      city=city,
      street=street
    )

    login(request, user)
    messages.success(request, f"{username}さんの登録が完了しました")
    return redirect('home')



class UserLoginView(FormView):
  template_name = 'users/user_login.html'
  form_class = UserLoginForm
  success_url = reverse_lazy('home')

  def form_valid(self, form):
    email = form.cleaned_data['email']
    password = form.cleaned_data['password']
    user = authenticate(email=email, password=password)
    if user:
      login(self.request, user)
      messages.success(self.request, f'おかえりなさい、{user.username}さん')
      return super().form_valid(form)
    else:
      messages.error(self.request, 'メールアドレスまたはパスワードが間違っています')
      return self.form_invalid(form)
    

class UserLogoutView(View):
  def get(self, request, *args, **kwargs):
    return render(request, 'users/user_logout.html')
  def post(self, request, *args, **kwargs):
    logout(request)
    return redirect('home')
  

class UserView(LoginRequiredMixin, TemplateView):
  template_name = 'users/user.html'

  def get_context_data(self, **kwargs):
    context = super().get_context_data(**kwargs)
    orders = Order.objects.filter(user=self.request.user).order_by('-created_at')

    for order in orders:  
      order.items_with_total = []
      for item in order.items.all():
        item.total_price = item.product.price * item.quantity
        order.items_with_total.append(item)
    context['orders'] = orders

    try:
      address = Address.objects.get(user=self.request.user)
      address_str = f"{address.prefecture}{address.city}{address.street}"
    except Address.DoesNotExist:
      address_str = "住所未登録"

    context['address_str'] = address_str
    return context
  
class UserForm(forms.ModelForm):
  class Meta:
    model = User
    fields = ['username', 'email']

class AddressForm(forms.ModelForm):
  class Meta:
    model = Address
    fields = ['postal_code', 'country', 'prefecture', 'city', 'street']

class EditUserAndAddressView(LoginRequiredMixin, View):
  def get(self, request):
    countries = get_country_list()
    user_form = UserForm(instance=request.user)
    address, created = Address.objects.get_or_create(user=request.user)
    address_form = AddressForm(instance=address)
    return render(request, 'users/edit.html', {
      'user_form': user_form,
      'address_form': address_form,
      "countries": countries,
      "prefectures": PREFECTURES
    })

  def post(self, request):
    user_form = UserForm(request.POST, instance=request.user)
    address, _ = Address.objects.get_or_create(user=request.user)
    address_form = AddressForm(request.POST, instance=address)

    if user_form.is_valid() and address_form.is_valid():
      user_form.save()
      address_form.save()
      messages.success(request, 'ユーザー情報を更新しました')
      return redirect('users:user')
    
    return render(request, 'users/edit.html', {
      'user_form': user_form,
      'address_form': address_form
    })

base_shop/templates/users/base.html
<!DOCTYPE html>
<html>
<head>
<meta charset="utf-8">
<link
href="https://cdn.jsdelivr.net/npm/bootstrap@5.0.2/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-EVSTQN3/azprG1Anm3QDgpJLIm9Nao0Yz1ztcQTwFspd3yD65VohhpuuCOmLASjC" crossorigin="anonymous">
</head>
<body>
<nav class="navbar navbar-expand-lg navbar-light bg-light">
<a class="navbar-brand" href="{% url 'users:home' %}">ホーム</a>
{% if user.is_authenticated %}
<a class="navbar-brand" href="{% url 'users:user_logout' %}">ログアウト</a>
<a class="navbar-brand" href="{% url 'users:user' %}">マイページへ</a>
{% else %}
<a class="navbar-brand" href="{% url 'users:user_login' %}">ログイン</a>
<a class="navbar-brand" href="{% url 'users:regist' %}">ユーザー登録</a>
<a class="navbar-brand" href="{% url 'products:home' %}">管理者ログイン</a>
{% endif %}
</nav>
{% if messages %}
  <ul class="messages text-danger">
    {% for message in messages %}
      <li class="{{ message.tags }}">{{ message }}</li>
    {% endfor %}
  </ul>
{% endif %}
{% block content %}
{% endblock %}
<script src="https://cdn.jsdelivr.net/npm/bootstrap@5.0.2/dist/js/bootstrap.bundle.min.js" integrity="sha384-MrcW6ZMFYlzcLA8Nl+NtUVF0sA7MsXsP1UyJoMp4YLEuNSfAP+JcXn/tWtIaxVXM" crossorigin="anonymous"></script>
</body>
</html>

base_shop/templates/users/edit.html
{% extends 'base.html' %}
{% block title %}ユーザー編集{% endblock %}
{% load static %}
{% block content %}

<div class="py-5 text-center">
  <h2>ユーザー情報編集</h2>
</div>
<div class="container w-50 mx-auto">
  <form class="needs-validation" novalidate="" method="POST">
    {% csrf_token %}
    <div class="row g-3">
      <div class="col-12 w-50">
        <label for="username" class="form-label">名前</label>
        <div class="input-group has-validation">
          <input type="text" class="form-control" name="username" required="" value="{{user_form.username.value}}">
          <div class="invalid-feedback">
            名前は必須です
          </div>
        </div>
      </div>
      <div class="col-12 w-100">
        <label for="email" class="form-label">メールアドレス</label>
        <input type="email" class="form-control" name="email" value="{{user_form.email.value}}">
        <div class="invalid-feedback">
          メールアドレスは必須です
        </div>
      </div>
      <div class="col-12 w-50">
        <label for="zip" class="form-label">郵便番号</label>
        <input type="text" class="form-control" name="postal_code" placeholder="123-4567" required=""
          value="{{address_form.postal_code.value}}">
        <div class="invalid-feedback">
          郵便番号は必須です
        </div>
      </div>
      <div class="col-12 w-50">
        <label for="country" class="form-label">国名</label>
        <select class="form-select" name="country" required="">
          <option value="">選択</option>
          {% for country in countries %}
          <option value="{{country}}" {% if address_form.country.value == country %}selected {% endif %}>{{country}}
          </option>
          {% endfor %}
        </select>
        <div class="invalid-feedback">
          国名は必須です
        </div>
      </div>
      <div class="col-12 w-50">
        <label for="state" class="form-label">都道府県</label>
        <select class="form-select" name="prefecture" required="">
          <option value="">選択</option>
          {% for prefecture in prefectures %}
          <option value="{{prefecture}}" {% if address_form.prefecture.value == prefecture %}selected {% endif %}>{{prefecture}}</option>
          {% endfor %}
        </select>
        <div class="invalid-feedback">
          都道府県は必須です
        </div>
      </div>
    </div>
    <div class="col-12 w-75 mt-3">
      <label for="address" class="form-label">市区町村</label>
      <input type="text" class="form-control" name="city" placeholder="港区" required=""
        value="{{address_form.city.value}}">
      <div class="invalid-feedback">
        市区町村は必須です
      </div>
    </div>
    <div class="col-12 mt-3">
      <label for="address2" class="form-label">丁目以下</label>
      <input type="text" class="form-control" name="street" placeholder="麻布十番1-2-3"
        value="{{address_form.street.value}}">
    </div>
    <hr class="my-4">
    <div class="col12 w-50 mx-auto text-center mb-4 d-flex justify-content-between">
      <a href="{% url 'users:user' %}" class="btn btn-secondary ms-2">キャンセル</a>
      <button class="button w-25" type="submit">更新</button>
    </div>
  </form>
</div>
{% endblock %}

base_shop/templates/users/regist.html
{% extends 'base.html' %}
{% load static %}
{% block title %}ユーザー登録{% endblock %}

{% block content %}

<div class="py-5 text-center">
      <h2>新規登録</h2>
</div>
<div class="container w-50 mx-auto">
  <form class="needs-validation" novalidate="" method="POST">
    {% csrf_token %}
    <div class="row g-3">
      <div class="col-12 w-50">
        <label for="username" class="form-label">名前</label>
        <div class="input-group has-validation">
          <input type="text" class="form-control" name="username" placeholder="TestTaro" required="">
          <div class="invalid-feedback">
            名前は必須です
          </div>
        </div>
      </div>
      <div class="col-12 w-100">
        <label for="email" class="form-label">メールアドレス</label>
        <input type="email" class="form-control" name="email" placeholder="test@example.com">
        <div class="invalid-feedback">
          メールアドレスは必須です
        </div>
      </div>
      <div class="col-12 w-100">
        <label for="email" class="form-label">パスワード</label>
        <input type="password" class="form-control" name="password" placeholder="">
        <div class="invalid-feedback">
          パスワードは必須です
        </div>
      </div>
      <div class="col-12 w-50">
        <label for="zip" class="form-label">郵便番号</label>
        <input type="text" class="form-control" name="postal_code" placeholder="123-4567" required="">
        <div class="invalid-feedback">
          郵便番号は必須です
        </div>
      </div>
      <div class="col-12 w-50">
        <label for="country" class="form-label">国名</label>
        <select class="form-select" name="country" required="">
          <option value="">選択</option>
          {% for country in countries %}
          <option value="{{country}}">{{country}}</option>
          {% endfor %}
        </select>
        <div class="invalid-feedback">
          国名は必須です
        </div>
      </div>
      <div class="col-12 w-50">
        <label for="state" class="form-label">都道府県</label>
        <select class="form-select" name="prefecture" required="">
          <option value="">選択</option>
          {% for prefecture in prefectures %}
          <option value="{{prefecture}}">{{prefecture}}</option>
          {% endfor %}
        </select>
        <div class="invalid-feedback">
          都道府県は必須です
        </div>
      </div>
    </div>
    <div class="col-12 w-75 mt-3">
      <label for="address" class="form-label">市区町村</label>
      <input type="text" class="form-control" name="city" placeholder="港区" required="">
      <div class="invalid-feedback">
        市区町村は必須です
      </div>
    </div>
    <div class="col-12 mt-3">
      <label for="address2" class="form-label">丁目以下</label>
      <input type="text" class="form-control" name="street" placeholder="麻布十番1-2-3">
    </div>
    <hr class="my-4">
    <div class="col12 w-50 mx-auto text-center mb-4 d-flex justify-content-between">
      <a href="{% url 'home' %}" class="btn btn-secondary ms-2">キャンセル</a>
      <button class="button w-25" type="submit">登録</button>
    </div>
  </form>
</div>
{% endblock %}

base_shop/templates/users/user.html
{% extends 'base.html' %}
{% block title %}マイページ{% endblock %}
{% load static %}

{% block content %}
<div class="container mt-5">
  <h2 class="text-center">マイページ</h2>

  <h4 class="w-50 mx-auto mt-5">ユーザー情報</h4>
  <table class="table table-bordered w-50 mx-auto">
    <tbody>
      <tr>
        <th class="w-25 py-3 ps-2">ユーザー名</th>
        <td class="py-3 ps-2">{{ user.username }}</td>
      </tr>
      <tr>
        <th class="py-3 ps-2">メールアドレス</th>
        <td class="py-3 ps-2">{{ user.email }}</td>
      </tr>
      <tr>
        <th class="py-3 ps-2">住所</th>
        <td class="py-3 ps-2">{{ address_str }}</td>
      </tr>
      <tr>
        <th class="py-3 ps-2">パスワード</th>
        <td class="py-3 ps-2 user_table_pass">⚫︎⚫︎⚫︎⚫︎⚫︎⚫︎⚫︎⚫︎⚫︎⚫︎⚫︎⚫︎</td>
      </tr>
    </tbody>
  </table>
  <div class="text-center">
    <a href="{% url 'users:edit' %} " class="button user_edit_btn">編集</a>
  </div>

  <h4 class="w-50 mx-auto mt-5">購入履歴</h4>

{% if orders %}
  {% for order in orders %}
    <div class="card mb-3 w-50 mx-auto {% if forloop.counter > 3 %}d-none extra-order{% endif %}">
      <div class="card-header">
        購入日: {{ order.created_at|date:"Y年m月d日" }}
      </div>
      <ul class="list-group list-group-flush">
        {% for item in order.items_with_total %}
          <li class="list-group-item">
            <strong>{{ item.product.name }}</strong> x {{ item.quantity }}
            <span class="float-end">¥{{ item.total_price|floatformat:0 }}</span>
          </li>
        {% endfor %}
      </ul>
    </div>
  {% endfor %}

  {% if orders|length > 3 %}
    <div class="text-center mt-3 mb-4">
      <button id="toggle-orders-btn" class="btn btn-link">もっと見る</button>
    </div>
  {% endif %}

{% else %}
  <p class="text-center">購入履歴はありません。</p>
{% endif %}


</div>
{% endblock %}

base_shop/templates/users/user_login.html
{% extends 'base.html' %}
{% load static %}
{% block title %}ログイン{% endblock %}

{% block content %}
<div class="container my-5 w-50 mx-auto text-center">
  <form method="POST">
    <h2 class="h3 mb-3 fw-normal">ログイン</h2>
    {% csrf_token %}
    <div class="form-group w-50 mx-auto mt-5 text-start">
      <label for="id_email" class="form-label">メールアドレス</label>
      <input type="email" name="email" class="form-control" id="id_email" placeholder="name@example.com">
    </div>
    <div class="form-group w-50 mx-auto mt-5 text-start">
      <label for="id_password" class="form-label">パスワード</label>
      <input type="password" name="password" class="form-control" id="id_password" placeholder="password">
    </div>
    <div class="mt-5 w-50 mx-auto d-flex justify-content-between">
      <a href="{% url 'home' %}" class="btn btn-secondary ms-5 mt-3">キャンセル</a>
      <button class="button me-5 mt-3" type="submit">ログイン</button>
    </div>
  </form>
</div>
{% endblock %}