base_shop/base_shop/urls.py
from django.contrib import admin
from django.urls import path,include
from django.shortcuts import redirect
from django.conf.urls.static import static # 画像用
from django.conf import settings # 画像用

urlpatterns = [
    path('admin/logout/', lambda request: redirect('/products/home/')),
    path('admin/', admin.site.urls),
    path('users/', include('users.urls')),
    path('products/', include('products.urls')),
    path('orders/', include('orders.urls')),
    path('', include('home.urls')),
]
urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT) # 画像用

base_shop/home/urls.py
from django.urls import path
from .views import HomeView
from . import views

urlpatterns = [
    path('', HomeView.as_view(), name='home'),  
    path('error-test/', views.trigger_error, name='error_test'),
]

base_shop/orders/urls.py
from django.urls import path
from . import views

app_name = 'orders'

urlpatterns = [
  path('cart/', views.view_cart, name='view_cart'),
  path('add/<product_id>/', views.add_to_cart, name='add_to_cart'),
  path('remove/<item_id>/', views.remove_from_cart, name='remove_from_cart'),
  path('confirm/', views.order_confirm_view, name='confirm'),
  path('complete/', views.order_complete_view, name='order_complete'),
  path('address', views.change_address_view, name='address'),
  path('buy-now/<product_id>/', views.buy_now, name='buy_now')
]

base_shop/products/urls.py
from django.urls import path
from . import views
from .views import ProductListView, ProductDetailView

app_name = 'products'

urlpatterns = [
  path('home/', views.HomeView.as_view(), name='home'),
  path('admin_login/', views.AdminLoginView.as_view(), name='admin_login'),
  path('list/', ProductListView.as_view(), name='product_list'),
  path('detail/<slug>', ProductDetailView.as_view(), name='product_detail')
]

base_shop/users/urls.py
from django.urls import path
from .views import (
RegistUserView, UserLoginView,
UserLogoutView,UserView,EditUserAndAddressView
)
from . import views

app_name = 'users'
urlpatterns = [
path('regist/', RegistUserView.as_view(), name='regist'),
path('login/', UserLoginView.as_view(), name='user_login'),
path('logout/', UserLogoutView.as_view(), name='user_logout'),
path('user/', UserView.as_view(), name='user'),
path('edit/', views.EditUserAndAddressView.as_view(), name='edit')
]

base_shop/home/models.py
from django.db import models

# Create your models here.

base_shop/users/models.py
from django.db import models
from django.contrib.auth.models import(
BaseUserManager, AbstractBaseUser, PermissionsMixin
)
from django.urls import reverse_lazy

class UserManager(BaseUserManager):
  def create_user(self, username, email, password):
    if not email:
      raise ValueError('Emailを入力してください')
    if not password:
      raise ValueError('Passwordを入力してください')
    user = self.model(
    username=username,
    email=self.normalize_email(email)
    )
    user.set_password(password)
    user.save()
    return user
  
  def create_superuser(self, username, email, password=None):
    user = self.create_user(
      username=username,
      email=email,
      password=password,
    )
    user.is_staff = True
    user.is_superuser = True
    user.save(using=self._db)
    return user

class User(AbstractBaseUser, PermissionsMixin):
  username = models.CharField('名前' ,max_length=150)
  email = models.EmailField('メールアドレス' ,max_length=255, unique=True)
  is_active = models.BooleanField(default=True)
  is_staff = models.BooleanField(default=False)
  is_superuser = models.BooleanField(default=False)

  USERNAME_FIELD = 'email'
  REQUIRED_FIELDS = ['username']
  
  objects = UserManager()
  
  def get_absolute_url(self):
    return reverse_lazy('users:home')

class Address(models.Model):
  user = models.OneToOneField(User, on_delete=models.CASCADE, related_name='address')
  postal_code = models.CharField('郵便番号' , max_length=10, blank=True, null=True)
  country = models.CharField('国名' , max_length=50, blank=True, null=True)
  prefecture = models.CharField('都道府県' , max_length=50, blank=True, null=True)
  city = models.CharField('市区町村' , max_length=100, blank=True, null=True)
  street = models.CharField('番地以下' , max_length=255, blank=True, null=True)

  def __str__(self):
    parts = [self.postal_code,self.country, self.prefecture, self.city, self.street]
    return " ".join(filter(None, parts)) or "住所未設定"

base_shop/users/forms.py
from django import forms
from .models import User
from django.contrib.auth.password_validation import validate_password

class RegistForm(forms.ModelForm):

  class Meta:
    model = User
    fields = ['username', 'email', 'password']
    widgets = {
    'password': forms.PasswordInput(),
    }
    labels = {
    'username': 'お名前(フルーネーム)',
    'email': 'メールアドレス',
    'password': 'パスワード',
    }

  def save(self, commit=False):
    user = super().save(commit=False)
    validate_password(self.cleaned_data['password'], user)
    user.set_password(self.cleaned_data['password'])
    user.save()
    return user
  
  def __init__(self, *args, **kwargs):
    super().__init__(*args, **kwargs)
    self.label_suffix = ''

class UserLoginForm(forms.Form):
  email = forms.EmailField(label='メールアドレス', label_suffix='')
  password = forms.CharField(label='パスワード', widget=forms.PasswordInput(), label_suffix='')

base_shop/home/views.py
from django.views.generic import TemplateView

class HomeView(TemplateView):
  template_name = 'home/home.html'
  
def trigger_error(request):
    raise Exception("これはテスト用のサーバーエラーです")

base_shop/users/views.py
from django.shortcuts import render, redirect
from django.views.generic import(
TemplateView, CreateView, FormView, View,UpdateView
)
from django.contrib.auth import authenticate, login, logout, get_user_model
from django.contrib.auth.mixins import LoginRequiredMixin
from django.urls import reverse_lazy
from django.contrib import messages
from django.views import View
from django import forms
from orders.models import Order
from .models import Address
from .forms import UserLoginForm
import pycountry

User = get_user_model()

PREFECTURES = ["北海道", "青森県", "岩手県", "宮城県", "秋田県", "山形県", "福島県", "茨城県", "栃木県", "群馬県", "埼玉県", "千葉県", "東京都", "神奈川県", "新潟県", "富山県", "石川県", "福井県", "山梨県", "岐阜県", "静岡県", "愛知県", "滋賀県", "京都府", "大阪府", "兵庫県", "奈良県", "和歌山県", "鳥取県", "島根県", "岡山県", "秋田県", "広島県", "山口県", "徳島県", "香川県", "愛媛県", "高知県", "福岡県", "佐賀県", "長崎県", "熊本県", "大分県", "宮崎県", "鹿児島県", "沖縄県"]

def get_country_list():
  return [country.name for country in pycountry.countries]

class RegistUserView(View):
  def get(self, request, *args, **kwargs):
    countries = get_country_list()
    return render(request, 'users/regist.html', {
      "countries": countries,
      "prefectures": PREFECTURES
    })
  
  def post(self, request, *args, **kwargs):
    # ユーザー情報の取得
    username = request.POST.get('username')
    email = request.POST.get('email')
    password = request.POST.get('password')

    # 住所情報の取得
    postal_code = request.POST.get('postal_code') or ""
    country = request.POST.get('country') or ""
    prefecture = request.POST.get('prefecture') or ""
    city = request.POST.get('city') or ""
    street = request.POST.get('street') or ""

    # 名前・メールアドレス・パスワードどれかがなかった場合の処理
    if not username or not email or not password:
      messages.error(request, "名前・メールアドレス・パスワード全て必須です")
      return render(request, 'users/regist.html')
    
    # メールアドレスが重複したいた場合の処理
    if User.objects.filter(email=email).exists():
      messages.error(request, "このメールアドレスは既に登録されています")
      return render(request, 'users/regist.html')
    
    #ユーザー情報の登録処理
    user = User.objects.create(
      username=username,
      email=email
    )
    user.set_password(password)
    user.save()

    #住所情報の登録処理
    Address.objects.create(
      user=user,
      postal_code=postal_code,
      country=country,
      prefecture=prefecture,
      city=city,
      street=street
    )

    login(request, user)
    messages.success(request, f"{username}さんの登録が完了しました")
    return redirect('home')



class UserLoginView(FormView):
  template_name = 'users/user_login.html'
  form_class = UserLoginForm
  success_url = reverse_lazy('home')

  def form_valid(self, form):
    email = form.cleaned_data['email']
    password = form.cleaned_data['password']
    user = authenticate(email=email, password=password)
    if user:
      login(self.request, user)
      messages.success(self.request, f'おかえりなさい、{user.username}さん')
      return super().form_valid(form)
    else:
      messages.error(self.request, 'メールアドレスまたはパスワードが間違っています')
      return self.form_invalid(form)
    

class UserLogoutView(View):
  def get(self, request, *args, **kwargs):
    return render(request, 'users/user_logout.html')
  def post(self, request, *args, **kwargs):
    logout(request)
    return redirect('home')
  

class UserView(LoginRequiredMixin, TemplateView):
  template_name = 'users/user.html'

  def get_context_data(self, **kwargs):
    context = super().get_context_data(**kwargs)
    orders = Order.objects.filter(user=self.request.user).order_by('-created_at')

    for order in orders:  
      order.items_with_total = []
      for item in order.items.all():
        item.total_price = item.product.price * item.quantity
        order.items_with_total.append(item)
    context['orders'] = orders

    try:
      address = Address.objects.get(user=self.request.user)
      address_str = f"{address.prefecture}{address.city}{address.street}"
    except Address.DoesNotExist:
      address_str = "住所未登録"

    context['address_str'] = address_str
    return context
  
class UserForm(forms.ModelForm):
  class Meta:
    model = User
    fields = ['username', 'email']

class AddressForm(forms.ModelForm):
  class Meta:
    model = Address
    fields = ['postal_code', 'country', 'prefecture', 'city', 'street']

class EditUserAndAddressView(LoginRequiredMixin, View):
  def get(self, request):
    countries = get_country_list()
    user_form = UserForm(instance=request.user)
    address, created = Address.objects.get_or_create(user=request.user)
    address_form = AddressForm(instance=address)
    return render(request, 'users/edit.html', {
      'user_form': user_form,
      'address_form': address_form,
      "countries": countries,
      "prefectures": PREFECTURES
    })

  def post(self, request):
    user_form = UserForm(request.POST, instance=request.user)
    address, _ = Address.objects.get_or_create(user=request.user)
    address_form = AddressForm(request.POST, instance=address)

    if user_form.is_valid() and address_form.is_valid():
      user_form.save()
      address_form.save()
      messages.success(request, 'ユーザー情報を更新しました')
      return redirect('users:user')
    
    return render(request, 'users/edit.html', {
      'user_form': user_form,
      'address_form': address_form
    })

base_shop/templates/base.html
{% load static %}
<!DOCTYPE html>
<html>

<head>
  <meta charset="utf-8">
  <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.3.0/dist/css/bootstrap.min.css" rel="stylesheet"
    integrity="sha384-9ndCyUaIbzAi2FUVXJi0CjmCapSmO7SnpJef0486qhLnuZ2cdeRhO02iuK6FUUVM" crossorigin="anonymous">
  <link rel="preconnect" href="https://fonts.googleapis.com">
  <link rel="preconnect" href="https://fonts.gstatic.com" crossorigin>
  <link href="https://fonts.googleapis.com/css2?family=Pinyon+Script&display=swap" rel="stylesheet">
  <link rel="stylesheet" href="{% static 'css/style.css' %}">
  <title>{% block title %} {% endblock %}</title>
</head>

<body>
    <header class="bg-primary-subtle text-emphasis-primary">
      <div class="base_header">
        <div class="header_logo">
          <img src="{% static 'images/logo.jpeg' %}" alt="画像" height="60" width="50" class="header_logo_img">
        </div>
        <a href="{% url 'home' %}" class="header_title_link">
          <h1 class="heaer_title">base_shop</h1>
        </a>
      </div>
      <nav class="navbar navbar-expand-lg bg-primary-subtle text-emphasis-primary base-nav">
        <div class="container-fluid">
          <div class="collapse navbar-collapse" id="navbarNav">
            <ul class="navbar-nav">
              <li class="nav-item">
                <a class="nav-link" href="{% url 'home' %}">
                  <div class="header_image_container">
                    <img src="{% static 'images/home.png' %}" alt="home画像"  class="header_nav_img">
                    <div class="caption">ホーム</div>
                  </div>
                </a>
              </li>
              {% if user.is_authenticated %}
              <li class="nav-item">
                <a class="nav-link" href="{% url 'users:user' %}">
                  <div class="header_image_container">
                    <img src="{% static 'images/mypage.png' %}" alt="mypage画像"  class="header_nav_img">
                    <div class="caption">マイページ</div>
                  </div>
                </a>
              </li>
              <li class="nav-item">
                <a class="nav-link" href="{% url 'orders:view_cart' %}">
                  <div class="header_image_container">
                    <img src="{% static 'images/cart.png' %}" alt="cart画像"  class="header_nav_img">
                    <div class="caption">カート</div>
                  </div>
                </a>
              </li>
              <li class="nav-item">
                <form method="POST" action="{% url 'users:user_logout' %}" class="nav-link">
                  {% csrf_token %}
                  <button type="submit" class="header_image_container" style="border: none; background: none;">
                      <img src="{% static 'images/logout.png' %}" alt="logout画像"  class="header_nav_img">
                      <div class="caption">ログアウト</div>
                  </button>
                  
                </form>
              </li>
              {% else %}
              <li class="nav-item">
                <a class="nav-link" href="{% url 'users:user_login' %}">
                  <div class="header_image_container">
                    <img src="{% static 'images/login.png' %}" alt="login画像"  class="header_nav_img">
                    <div class="caption">ログイン</div>
                  </div>
                </a>
              </li>
              <li class="nav-item">
                <a class="nav-link" href="{% url 'users:regist' %}">
                  <div class="header_image_container">
                    <img src="{% static 'images/regist.png' %}" alt="regist画像"  class="header_nav_img">
                    <div class="caption">ユーザー登録</div>
                  </div>
                </a>
              </li>
              <li class="nav-item administrator_item">
                <a class="nav-link " href="{% url 'products:home' %}">管理者ログイン</a>
              </li>
              {% endif %}
            </ul>
          </div>
      </nav>
      </div>
    </header>
    {% if messages %}
    {% for message in messages %}
      <div class="alert alert-info alert-dismissible fade show mt-4 w-25 base-fade-in " role="alert">
        {{message}}
        <button type="button" class="btn-close" data-bs-dismiss="alert" aria-label="Close"></button>
      </div>
    {% endfor %}
    {% endif %}
    <main>
      {% block content %}
      {% endblock %}
    </main>
    <footer class="bg-primary-subtle text-emphasis-primary">
      <small>©︎2025 <span class="footer_title">base_shop</span></small>
    </footer>
  <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.3.0/dist/js/bootstrap.bundle.min.js"
    integrity="sha384-geWF76RCwLtnZ8qwWowPQNguL3RmwHVBC9FhGdlKrxdiJJigb/j/68SIy3Te4Bkz"
    crossorigin="anonymous"></script>
    <script src="{% static 'js/main.js' %}"></script>
</body>
</html>

base_shop/templates/home.html
{% extends 'base.html' %}
{% block content %}
<h1>ホーム画面</h1>
{% endblock %}

base_shop/templates/regist.html
{% extends 'base.html' %}
{% block content %}
<form method="POST">
  {% csrf_token %}
  {{ form.as_p }}
  <input type="submit" value="ユーザー登録">
</form>
{% endblock %}

base_shop/templates/user.html
{% extends 'base.html' %}
{% block content %}
<h2>マイページ</h2>

<p><strong>名前：</strong> {{ user.username }}</p>
{% endblock %}

base_shop/templates/user_logout.html
{% extends 'base.html' %}
{% block content %}
<form method="POST">
  {% csrf_token %}
  <input type="submit" value="ログアウト">
</form>
{% endblock %}