base_shop/base_shop/urls.py
from django.contrib import admin
from django.urls import path,include
from django.shortcuts import redirect
from django.conf.urls.static import static # 画像用
from django.conf import settings # 画像用

urlpatterns = [
    path('admin/logout/', lambda request: redirect('/products/home/')),
    path('admin/', admin.site.urls),
    path('users/', include('users.urls')),
    path('products/', include('products.urls')),
    path('orders/', include('orders.urls')),
    path('', include('home.urls')),
]
urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT) # 画像用

base_shop/home/urls.py
from django.urls import path
from .views import HomeView
from . import views

urlpatterns = [
    path('', HomeView.as_view(), name='home'),  
    path('error-test/', views.trigger_error, name='error_test'),
]

base_shop/orders/urls.py
from django.urls import path
from . import views

app_name = 'orders'

urlpatterns = [
  path('cart/', views.view_cart, name='view_cart'),
  path('add/<product_id>/', views.add_to_cart, name='add_to_cart'),
  path('remove/<item_id>/', views.remove_from_cart, name='remove_from_cart'),
  path('confirm/', views.order_confirm_view, name='confirm'),
  path('complete/', views.order_complete_view, name='order_complete'),
  path('address', views.change_address_view, name='address'),
  path('buy-now/<product_id>/', views.buy_now, name='buy_now')
]

base_shop/products/urls.py
from django.urls import path
from . import views
from .views import ProductListView, ProductDetailView

app_name = 'products'

urlpatterns = [
  path('home/', views.HomeView.as_view(), name='home'),
  path('admin_login/', views.AdminLoginView.as_view(), name='admin_login'),
  path('list/', ProductListView.as_view(), name='product_list'),
  path('detail/<slug>', ProductDetailView.as_view(), name='product_detail')
]

base_shop/orders/models.py
from django.db import models
from django.conf import settings
from products.models import Product
from users.models import User
from django.contrib.auth import get_user_model

User = get_user_model()

# Create your models here.
class Cart(models.Model):
  user = models.OneToOneField(settings.AUTH_USER_MODEL, on_delete=models.CASCADE)

  def __str__(self):
    return f"{self.user.username}のカート"
  
  def get_total_price(self):
    return sum(item.product.price * item.quantity for item in self.items.all())

class CartItem(models.Model):
  cart = models.ForeignKey(Cart, on_delete=models.CASCADE, related_name="items")
  product = models.ForeignKey(Product, on_delete=models.CASCADE)
  quantity = models.PositiveIntegerField(default=0)

  def __str__(self):
    return f"{self.product.name} x {self.quantity}"

class Order(models.Model):
  user = models.ForeignKey(User, verbose_name='購入者アドレス', on_delete=models.CASCADE)
  created_at = models.DateTimeField("購入日" ,auto_now_add=True)
  address = models.CharField("送付先住所" ,max_length=255)
  total_price = models.IntegerField("購入金額")

  def __str__(self):
    return f"{self.user.username}"
  
  class Meta:
    verbose_name = '購入履歴'
    verbose_name_plural = '購入一覧'
  
class OrderItem(models.Model):
  order = models.ForeignKey(Order, on_delete=models.CASCADE, related_name="items")
  product = models.ForeignKey(Product, on_delete=models.CASCADE, verbose_name="商品",)
  quantity = models.PositiveIntegerField('数量')

  def __str__(self):
    return f"{self.product.name} x {self.quantity}"
  

  class Meta:
    verbose_name = "注文商品"
    verbose_name_plural = "注文商品の一覧"

base_shop/orders/views.py
from django.shortcuts import render, redirect, get_object_or_404
from django.contrib.auth.decorators import login_required
from django.contrib import messages
from django.http import JsonResponse
from django.views.decorators.http import require_POST
from .models import Cart, CartItem, Order, OrderItem
from products.models import Product
from users.models import Address
import pycountry

PREFECTURES = ["北海道", "青森県", "岩手県", "宮城県", "秋田県", "山形県", "福島県", "茨城県", "栃木県", "群馬県", "埼玉県", "千葉県", "東京都", "神奈川県", "新潟県", "富山県", "石川県", "福井県", "山梨県", "岐阜県", "静岡県", "愛知県", "滋賀県", "京都府", "大阪府", "兵庫県", "奈良県", "和歌山県", "鳥取県", "島根県", "岡山県", "秋田県", "広島県", "山口県", "徳島県", "香川県", "愛媛県", "高知県", "福岡県", "佐賀県", "長崎県", "熊本県", "大分県", "宮崎県", "鹿児島県", "沖縄県"]

def get_country_list():
  return [country.name for country in pycountry.countries]

# カート表示
@login_required
def view_cart(request):
  cart, _ = Cart.objects.get_or_create(user=request.user)
  cart_items = cart.items.all()
  items_with_subtotals = []
  total_price = 0

  for item in cart_items:
        subtotal = item.product.price * item.quantity
        total_price += subtotal
        items_with_subtotals.append({
            'id': item.id,
            'product': item.product,
            'quantity': item.quantity,
            'subtotal': subtotal
        })
    
  referer = request.META.get('HTTP_REFERER', '/')

  return render(request, 'orders/cart_item.html', {
    'cart_items': items_with_subtotals,
    'total_price': total_price,
    'back_url': referer
    })

# カートに商品追加
@login_required
def add_to_cart(request, product_id):
  product = get_object_or_404(Product, id=product_id)
  cart, _ = Cart.objects.get_or_create(user=request.user)
  item, created = CartItem.objects.get_or_create(cart=cart, product=product)
  item.quantity += 1
  item.save()

  if request.headers.get('x-requested-with') == 'XMLHttpRequest':
    return JsonResponse({'name': product.name, 'quantity': item.quantity})

  return redirect('orders:view_cart')

# カートから商品削除
@login_required
def remove_from_cart(request, item_id):
  item = get_object_or_404(CartItem, id=item_id)
  if item.quantity > 1:
    item.quantity -= 1
    item.save()
  else:
    item.delete()
  referer = request.META.get('HTTP_REFERER', '/')
  return redirect(referer)

# 購入処理。購入後カート内商品は削除
@login_required
def order_confirm_view(request):
  cart = Cart.objects.filter(user=request.user).first()
  cart_items = cart.items.all()
  total_price = sum(item.product.price * item.quantity for item in cart_items)
  referer = request.META.get('HTTP_REFERER', '/')
  items_with_subtotals = []

  for item in cart_items:
    subtotal = item.product.price * item.quantity
    items_with_subtotals.append({
      'id': item.id,
      'product': item.product,
      'quantity': item.quantity,
      'subtotal':subtotal
    })

  if 'temporary_address' in request.session:
    ship_address = request.session['temporary_address']
  else:
    address = Address.objects.filter(user=request.user).first()
    if not address or not (address.postal_code and address.prefecture and address.city and address.street):
      messages.error(request, "住所が登録されていません。住所登録をしてください")
      return redirect('users:edit')
    ship_address = {
      'postal_code': address.postal_code,
      'country': address.country,
      'prefecture': address.prefecture,
      'city': address.city,
      'street': address.street
    }
  if request.method == 'POST':
    prefecture = request.POST.get('prefecture', "")
    city = request.POST.get('city', "")
    street = request.POST.get('street', "")
    address_str = f"{prefecture}{city}{street}"
    order = Order.objects.create(
      user=request.user,
      address=address_str,
      total_price=cart.get_total_price()
    )

    for item in cart.items.all():
      OrderItem.objects.create(
        order=order,
        product=item.product,
        quantity=item.quantity
      )
    cart.items.all().delete()
    if 'temporary_address' in request.session:
      del request.session['temporary_address']
    return redirect('orders:order_complete')
  
  return render(request, 'orders/order.html', {
    'cart_items':items_with_subtotals,
    'total_price':total_price,
    'address':ship_address,
    'back_url': referer
  })
  

def order_complete_view(request):
  return render(request, 'orders/complete.html')

@login_required
def change_address_view(request):
  address, _ = Address.objects.get_or_create(user=request.user)
  referer = request.META.get('HTTP_REFERER', '/')
  countries = get_country_list()
  if request.method == 'POST':
    postal_code = request.POST.get('postal_code', "")
    country = request.POST.get('country', "")
    prefecture = request.POST.get('prefecture', "")
    city = request.POST.get('city', "")
    street = request.POST.get('street', "")

    if postal_code and country and prefecture and city and street:
      request.session['temporary_address'] = {
        'postal_code': postal_code,
        'country': country,
        'prefecture': prefecture,
        'city': city,
        'street': street,
      }
      messages.success(request, 'お届け先住所を変更しました')
      return redirect('orders:confirm')
    else:
      messages.error(request, '全ての項目を入力してください')
  return render(request, 'orders/address.html', {
    'address':address,
    'back_url': referer,
    "countries": countries,
    "prefectures": PREFECTURES
  })

@login_required
def buy_now(request, product_id):
  product = get_object_or_404(Product, id=product_id)
  cart, _ = Cart.objects.get_or_create(user=request.user)
  item, created = CartItem.objects.get_or_create(cart=cart, product=product)
  item.quantity += 1
  item.save()

  return redirect('orders:confirm')

base_shop/templates/orders/address.html
{% extends 'base.html' %}
{% block title %}{{product.name}}住所変更{% endblock %}

{% block content %}
<div class="py-5 text-center">
  <h2>配送先住所変更</h2>
</div>
<div class="container w-50 mx-auto">
  <form class="needs-validation" novalidate="" method="POST">
    {% csrf_token %}
    <div class="row g-3">
      <div class="col-12 w-50">
        <label for="zip" class="form-label">郵便番号</label>
        <input type="text" class="form-control" name="postal_code" placeholder="123-4567" required=""
          value="{{address.postal_code}}">
        <div class="invalid-feedback">
          郵便番号は必須です
        </div>
      </div>
      <div class="col-12 w-50">
        <label for="country" class="form-label">国名</label>
        <select class="form-select" name="country" required="">
          <option value="">選択</option>
          {% for country in countries %}
          <option value="{{country}}" {% if address.country == country %}selected {% endif %}>{{country}}
          </option>
          {% endfor %}
        </select>
        <div class="invalid-feedback">
          国名は必須です
        </div>
      </div>
      <div class="col-12 w-50">
        <label for="state" class="form-label">都道府県</label>
        <select class="form-select" name="prefecture" required="">
          <option value="">選択</option>
          {% for prefecture in prefectures %}
          <option value="{{prefecture}}" {% if address.prefecture == prefecture %}selected {% endif %}>{{prefecture}}</option>
          {% endfor %}
        </select>
        <div class="invalid-feedback">
          都道府県は必須です
        </div>
      </div>
    </div>
    <div class="col-12 w-75 mt-3">
      <label for="address" class="form-label">市区町村</label>
      <input type="text" class="form-control" name="city" placeholder="港区" required="" value="{{address.city}}">
      <div class="invalid-feedback">
        市区町村は必須です
      </div>
    </div>
    <div class="col-12 mt-3">
      <label for="address2" class="form-label">丁目以下</label>
      <input type="text" class="form-control" name="street" placeholder="麻布十番1-2-3" value="{{address.street}}">
    </div>
    <hr class="my-4">
    <div class="col12 w-50 mx-auto text-center mb-4 d-flex justify-content-between">
      <a href="{% url 'orders:confirm' %}" class="button btn_back">購入画面へ戻る</a>
      <button class="button w-25" type="submit">変更</button>
    </div>
  </form>
</div>


{% endblock %}

base_shop/templates/orders/cart.html
{% extends 'base.html' %}
{% block title %}カート内商品一覧{% endblock %}

{% block content %}
  <h2>{{user.username}}のカート</h2>
  <ul>
    {% for item in cart.items.all %}
      <li>
        {{item.product.name}} - {{item.quantity}}個
        <a href="{% url 'orders:remove_from_cart' item.id %}">削除</a>
      </li>
    {% empty %}
      <li>カート内商品はありません</li>
    {% endfor %}
  </ul>
  <a href="{% url 'orders:confirm' %}">注文する</a><br>
  <button onclick="history.back()">戻る</button>
{% endblock %}

base_shop/templates/orders/cart_item.html
{% extends 'base.html' %}
{% load static %}
{% block title %}カート内商品一覧{% endblock %}

{% block content %}
<div class="container mt-5">
  <h2 class="text-center">カート内商品</h2>
  {% if cart_items %}
  {% for item in cart_items %}
  <div class="list-group-item d-flex align-items-center justify-content-between w-50 mx-auto mt-2">
      <img src="{{ item.product.image.url }}" alt="{{ item.product.name }}" class="img-thumbnail me-3 thumb_img_size" >
    
    <div class="d-flex flex-column align-items-end">
      <h5 class="mb-2">{{ item.product.name }}</h5>
      <p class="mb-2">￥{{ item.product.price }} × {{ item.quantity }}</p>
      <p class="mb-2">小計: ￥{{ item.subtotal }}</p>
      <a href="{% url 'orders:remove_from_cart' item.id %}" class="mb-2 button">削除</a>
    </div>
  </div>
  {% endfor %}
  <div class="my-3 w-50 mx-auto d-flex align-items-end justify-content-between ">
    <a href="{% url 'products:product_list' %}" class="button mb-0 cart_btn btn_back">商品一覧へ戻る</a>
    <div class="d-flex flex-column justify-content-between cart_wrapper">
      <h4 class="mb-2">合計金額: ¥{{total_price}}</h4>
      <a href="{% url 'orders:confirm' %}" class="button">購入手続きへ進む</a>
    </div>
  </div>

  {% else %}
  <p class="text-center">商品はありません</p>
  <a href="{% url 'products:product_list' %}" class="button cart_btn btn_back">商品一覧へ戻る</a>
  {% endif %}
</div>
{% endblock %}

base_shop/templates/orders/complete.html
{% extends 'base.html' %}
{% block title %}購入完了{% endblock %}

{% block content %}
<div class="container mt-5">
  <h2 class="text-center">ご注文ありがとうございました。</h2>
  <p class="text-center mt-3">注文が正常に完了しました。</p>
  <div class="text-center mt-4">
    <a href="{% url 'products:product_list' %}" class="button ">商品一覧に戻る</a>
  </div>
</div>
{% endblock %}

base_shop/templates/orders/order.html
{% extends 'base.html' %}
{% block title %}{{product.name}}注文確定{% endblock %}

{% block content %}
<div class="container mt-5">

  <h2 class="text-center">注文確定</h2>

  {% for item in cart_items %}
  <div class="list-group-item d-flex align-items-center justify-content-between w-50 mx-auto mt-4">
    <img src="{{ item.product.image.url }}" alt="{{ item.product.name }}" class="img-thumbnail me-3 thumb_img_size">
    <div class="d-flex flex-column align-items-end">
      <h5 class="mb-2">{{ item.product.name }}</h5>
      <p class="mb-2">￥{{ item.product.price }} × {{ item.quantity }}</p>
      <p><strong>小計: ￥{{item.subtotal}}</strong></p>
      <a href="{% url 'orders:remove_from_cart' item.id %}" class="mb-2 button">削除</a>
    </div>
  </div>
  {% endfor %}

  <div class="w-50 mx-auto mt-3">
    <div class="text-end ">
      <h4>合計金額: ¥{{total_price}}</h4>
      <div class="mt-3">
        <p class="m-0">お届け先住所:{{address.prefecture}}{{address.city}}{{address.street}}</p>
        <a href="{% url 'orders:address' %}">配送先住所を変更する</a><br>
      </div>
      <div class="mt-3">
        <label for="pay" class="mb-0 w-auto">お支払い方法:</label>
        <select id="pay" class=" w-auto order_select">
          <option selected>選択してください</option>
          <option value="cash">現金</option>
          <option value="credit">クレジットカード</option>
          <option value="convenience">コンビニ支払い</option>
        </select>
      </div>

    </div>
  </div>
  <div class="w-50 d-flex justify-content-between mx-auto my-5">
    <a href="{% url 'orders:view_cart' %}" class="button btn_back">カートに戻る</a>
    <a href="{% url 'products:product_list' %}" class="button mb-0  btn_back">商品一覧へ戻る</a>
    <form method="post" id="purchaseForm" action="{% url 'orders:confirm' %}">
      {% csrf_token %}
      <input type="hidden" name="prefecture" value="{{ address.prefecture }}">
      <input type="hidden" name="city" value="{{ address.city }}">
      <input type="hidden" name="street" value="{{ address.street }}">
      <!-- Button trigger modal -->
      <button type="button" class="button " data-bs-toggle="modal" data-bs-target="#confirmed_btn">
        注文を確定する
      </button>
    </form>
  </div>

  <!-- Modal -->
  <div class="modal fade" id="confirmed_btn" tabindex="-1" aria-hidden="true">
    <div class="modal-dialog">
      <div class="modal-content">
        <div class="modal-header">
          <button type="button" class="btn-close" data-bs-dismiss="modal" aria-label="Close"></button>
        </div>
        <div class="modal-body">
          購入を確定します。よろしいですか?
        </div>
        <div class="modal-footer d-flex justify-conntent-end ">
          <button type="button" class="btn btn-secondary me-4" data-bs-dismiss="modal">キャンセル</button>
          <button type="button" class="button btn-primary ms-4 px-4"
            onclick="document.getElementById('purchaseForm').submit();">購入する</button>
        </div>
      </div>
    </div>
  </div>

  <div class="text-center mt-3">

  </div>



</div>
{% endblock %}

base_shop/templates/orders/order_complete.html
{% extends 'base.html' %}
{% block title %}購入完了{% endblock %}

{% block content %}
  <h2>ご注文ありがとうございました。</h2>
  <p>注文が正常に完了しました。</p>
  <a href="{% url 'products:product_list' %}">商品一覧に戻る</a>
{% endblock %}

base_shop/templates/orders/order_confirm.html
{% extends 'base.html' %}
{% block title %}{{product.name}}注文確認{% endblock %}

{% block content %}
<h2>注文確認</h2>
<ul>
  {% for item  in cart_items %}
  <li>
    {{item.product.name}} ({{item.quantity}}個)
  </li>
  {% endfor %}
</ul>

<p>合計金額:{{cart.get_total_price}}円</p>

<form method="POST">
  {% csrf_token %}
  <p><strong>お届け先住所:</strong>{{address}}</p>
  <button type="submit">注文確定</button>
</form>
<button onclick="history.back()">戻る</button>

{% endblock %}